Models/DB/Carro.cs
using System;

namespace trab_crud.Models.DB
{
    public class Carro
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int AnoLancamento { get; set; }
        public int AnoMontagem { get; set; }
        public string Chassis { get; set; }
    }
}

Models/DB/Contato.cs
using System;

namespace trab_crud.Models.DB
{
    public class Contato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
    }
}

Models/DB/Produto.cs
using System;

namespace trab_crud.Models.DB
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public double Valor { get; set; }
        public int Estoque { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace trab_crud.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarroController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using trab_crud.Models.DB;
using trab_crud.Data;

namespace trab_crud.Controllers
{
    public class CarroController : Controller
    {
        private readonly ILogger<CarroController> _logger;

        private readonly appContext _context;

        public CarroController(ILogger<CarroController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            IList<Carro> carros = _context.Carros.ToList();
            return View();
        }

    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using trab_crud.Models.DB;
using trab_crud.Data;

namespace trab_crud.Controllers
{
    public class ContatoController : Controller
    {
        private readonly ILogger<ContatoController> _logger;

        private readonly appContext _context;

        public ContatoController(ILogger<ContatoController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            IList<Contato> contatos = _context.Contatos.ToList();
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using trab_crud.Models;

namespace trab_crud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;
using trab_crud.Models.DB;
using trab_crud.Data;

namespace trab_crud.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ILogger<ProdutoController> _logger;

        private readonly appContext _context;

        public ProdutoController(ILogger<ProdutoController> logger, appContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            IList<Produto> produtos = _context.Produtos.ToList();
            return View();
        }

    }
}

Views/Carro/Index.cshtml
@model IList<trab_crud.Models.DB.Carro>

@{
    ViewData["Title"] = "Tabelas";
}

<table class="table">
    <thead> 
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (trab_crud.Models.DB.Carro carro in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelCarro => carro.Id)</td>
                <td>@Html.DisplayFor(modelCarro => carro.Marca)</td>
                <td>@Html.DisplayFor(modelCarro => carro.Modelo)</td>
                <td>@Html.DisplayFor(modelCarro => carro.AnoLancamento)</td>
                <td>@Html.DisplayFor(modelCarro => carro.AnoMontagem)</td>
                <td>@Html.DisplayFor(modelCarro => carro.Chassis)</td>
            </tr>     
        }
    </tbody>
</table>

Views/Contato/Index.cshtml
@model IList<trab_crud.Models.DB.Contato>

@{
    ViewData["Title"] = "Tabelas";
}

<table class="table">
    <thead> 
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (trab_crud.Models.DB.Contato contato in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelContato => contato.Id)</td>
                <td>@Html.DisplayFor(modelContato => contato.Nome)</td>
                <td>@Html.DisplayFor(modelContato => contato.Email)</td>
                <td>@Html.DisplayFor(modelContato => contato.Telefone)</td>
            </tr>     
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Tabelas";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produto/Index.cshtml
@model IList<trab_crud.Models.DB.Produto>

@{
    ViewData["Title"] = "Tabelas";
}

<table class="table">
    <thead> 
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (trab_crud.Models.DB.Produto Produto in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelProduto => Produto.Id)</td>
                <td>@Html.DisplayFor(modelProduto => Produto.Nome)</td>
                <td>@Html.DisplayFor(modelProduto => Produto.Valor)</td>
                <td>@Html.DisplayFor(modelProduto => Produto.Estoque)</td>
            </tr>     
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - trab_crud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">trab_crud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - trab_crud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>